import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from "./components/SideMenu";
import { BsGithub } from "react-icons/bs";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-transparent p-5 px-10 pt-8 absolute left-0 right-0 flex justify-between">
          {/* <p className='text-white'>Squig</p> */}
          <SideMenu />
          <Link href={"https://github.com/Harish-M-2003/Squig"} target="_blank">
            <BsGithub className={"text-4xl text-gray-400"} />
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
