// "use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from "./components/SideMenu";
import { BsGithub } from "react-icons/bs";
import Link from "next/link";
import Head from "next/head";

// import { useEffect } from "react";
// import { once } from "events";
// import Aos from "aos";

// AOS.init();

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  // useEffect(()=>{
  //   // Aos.init()
  //   AOS.init({
  //     easing :"ease-in-out",
  //     once : true,
  //     offset : 50,
  //   })
  // } , [])
  return (
    <html lang="en">
      {/* <Head>
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script>{AOS.init()}</script>
      </Head> */}
      <body>
        <nav className="bg-transparent p-5 md:px-10 px-5 md:pt-8 pt-4 absolute left-0 right-0 flex justify-between">
          {/* <p className='text-white'>Squig</p> */}
          <SideMenu />
          <Link href={"https://github.com/Harish-M-2003/Squig"} target="_blank">
            <BsGithub className={"md:text-4xl text-2xl text-gray-400"} />
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
